name: taletime
description: TaleTime App.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any
  
  #Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  cloud_firestore_web: ^3.2.1
  firebase_storage: ^11.0.10
  firebase_storage_web: ^3.3.19
  firebase_core_web: ^2.1.0
  firebase_auth_web: ^5.2.4
  record: ^4.4.4
  path: ^1.8.2

  email_validator: ^2.0.1
  provider: ^6.0.3
  hexcolor: ^3.0.1
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  image_picker: ^0.8.5+3
  marquee: ^2.2.1
  file_picker: ^5.2.5
  flutter_sound: ^9.2.13
  permission_handler: ^10.0.2
  audioplayers: ^2.0.0
  audioplayers_web: ^2.1.1
  flutter_picker: ^2.0.5
  avatar_glow: ^2.0.2

  #share
  share: ^2.0.4

  #fluttertoast
  fluttertoast: ^8.0.8
  percent_indicator: ^3.0.2
  open_file: ^3.2.1

  image_picker_for_web: ^2.1.10
  path_provider: ^2.0.11
  flutter_sound_web: ^9.2.13
  flutter_web_plugins:
    sdk: flutter
  logger: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  lint: ^2.0.0
  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
