name: taletime
description: TaleTime App.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.1-SNAPSHOT

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any
  
  #Firebase
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.0
  cloud_firestore_web: ^3.11.0
  firebase_storage: ^11.7.0
  firebase_storage_web: ^3.8.1
  firebase_core_web: ^2.11.4
  firebase_auth_web: ^5.11.0
  record: ^5.0.5
  path: ^1.8.3

  email_validator: ^2.1.17
  provider: ^6.1.2
  hexcolor: ^3.0.1
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  image_picker: ^1.0.7
  marquee: ^2.2.3
  file_picker: ^8.0.0+1
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  audioplayers_web: ^5.0.0
  flutter_picker: ^2.1.0
  avatar_glow: ^3.0.1

  #share
  share_plus: ^8.0.2

  #fluttertoast
  fluttertoast: ^8.2.4
  percent_indicator: ^4.2.3
  open_file: ^3.3.2

  image_picker_for_web: ^3.0.3
  path_provider: ^2.1.2
  flutter_sound_web: ^9.2.13
  flutter_web_plugins:
    sdk: flutter
  logger: ^1.4.0

  url_launcher: ^6.2.5
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  audio_service: ^0.18.13
  just_audio: ^0.9.37
  go_router: ^13.2.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  lint: ^2.3.0
  flutter_lints: ^3.0.2

flutter:
  assets:
    - assets/
    - assets/profile/
  generate: true
  uses-material-design: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
