name: taletime
description: TaleTime App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  
  #Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10


  email_validator: ^2.0.1
  provider: ^6.0.3
  hexcolor: ^3.0.1
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  image_picker: ^0.8.5+3
  marquee: ^2.2.1
  file_picker: ^5.2.5
  flutter_sound: ^9.2.13
  permission_handler: ^10.0.2
  audioplayers: ^2.0.0
  flutter_picker: ^2.0.5
  avatar_glow: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0

flutter:
  generate: true
  uses-material-design: true


    

