name: taletime
description: TaleTime App.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.4-SNAPSHOT

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any
  
  #Firebase
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  cloud_firestore_web: ^3.8.5
  firebase_storage: ^11.5.1
  firebase_storage_web: ^3.6.13
  firebase_core_web: ^2.8.1
  firebase_auth_web: ^5.8.7
  record: ^5.0.1
  path: ^1.8.3

  email_validator: ^2.1.17
  provider: ^6.1.1
  hexcolor: ^3.0.1
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  image_picker: ^1.0.4
  marquee: ^2.2.3
  file_picker: ^6.1.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  audioplayers: ^5.2.1
  audioplayers_web: ^4.1.0
  flutter_picker: ^2.1.0
  avatar_glow: ^2.0.2

  #share
  share_plus: ^7.2.1

  #fluttertoast
  fluttertoast: ^8.0.8
  percent_indicator: ^4.2.3
  open_file: ^3.2.1

  image_picker_for_web: ^3.0.1
  path_provider: ^2.0.11
  flutter_sound_web: ^9.2.13
  flutter_web_plugins:
    sdk: flutter
  logger: ^1.1.0

  url_launcher: ^6.2.1
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  lint: ^2.0.0
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
  generate: true
  uses-material-design: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
