name: Test and build Android app

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - '**.md'
      - 'doc/**'
      - '.git/'
      - '.vscode/'
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
      - name: 📦 Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: ⚙️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: 'stable'
            cache: true
            cache-key: 'flutter-linux'
      - name: 💵 Cache flutter build
        id: cache-primes
        uses: actions/cache@v4
        with:
           path: |
            ./taletime/build
             /opt/hostedtoolcache/flutter
           key: ${{ runner.os }}-flutter-build
      - name: 📦 Get dependencies
        run: flutter pub get
        working-directory: ./taletime
      - name: 🧪 Run tests
        run: flutter test
        working-directory: ./taletime
      - name: 📱 Build Android
        id: build_apk
        run: |
          rm -f build/app/outputs/flutter-apk/*.apk
          VERSION=$(grep -oP '^version:\s+\K.+$' pubspec.yaml)
          flutter build apk --flavor staging --build-name $VERSION+$GITHUB_RUN_NUMBER
          echo "versionName=$VERSION+$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT
        working-directory: ./taletime
      - name: 🔑 Sign app
        uses: ilharp/sign-android-release@v1
        id: sign_app
        with:
          releaseDir: taletime/build/app/outputs/flutter-apk
          signingKey: ${{ secrets.SIGNING_KEY_KEYSTORE }}
          keyAlias: "TaleTime-Key"
          keyStorePassword: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_KEY_PASSWORD }}
          buildToolsVersion: 33.0.0
      - name: 🏷 Rename APK file
        run: cp ${{ steps.sign_app.outputs.signedFile }} taletime/build/app/outputs/flutter-apk/TaleTime-${{ steps.build_apk.outputs.versionName }}.apk
      - name: 📦 Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TaleTime-${{ steps.build_apk.outputs.versionName }}.apk
          path: ./taletime/build/app/outputs/flutter-apk/TaleTime*.apk